# Generated by Django 4.1 on 2022-10-29 13:09

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Storage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unique identification",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date of creation"
                    ),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Publishingdate",
                    ),
                ),
                (
                    "date_expired",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiring date"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date of last update"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delete date"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in review", "In review"),
                            ("published", "Published"),
                            ("changes requested", "Changes requested"),
                            ("schedule", "Schedule"),
                        ],
                        default="draft",
                        max_length=255,
                    ),
                ),
                ("is_selected", models.BooleanField(default=False)),
                (
                    "storage_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("google", "Google Cloud Storage"),
                            ("aws", "Amazon S3"),
                        ],
                        default="aws",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "auth_file",
                    models.FileField(
                        blank=True, null=True, upload_to="storage/google/"
                    ),
                ),
                (
                    "project_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "access_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "secret_key",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "bucket_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "region",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "company",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
