# Generated by Django 4.1 on 2022-10-29 13:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TemplateCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unique identification",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date of creation"
                    ),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Publishingdate",
                    ),
                ),
                (
                    "date_expired",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiring date"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date of last update"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delete date"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in review", "In review"),
                            ("published", "Published"),
                            ("changes requested", "Changes requested"),
                            ("schedule", "Schedule"),
                        ],
                        default="draft",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "company",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "verbose_name": "Template Category",
                "verbose_name_plural": "Template Categories",
            },
        ),
        migrations.CreateModel(
            name="Template",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Unique identification",
                    ),
                ),
                (
                    "date_created",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date of creation"
                    ),
                ),
                (
                    "date_published",
                    models.DateTimeField(
                        blank=True,
                        default=django.utils.timezone.now,
                        null=True,
                        verbose_name="Publishingdate",
                    ),
                ),
                (
                    "date_expired",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Expiring date"
                    ),
                ),
                (
                    "date_updated",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date of last update"
                    ),
                ),
                (
                    "date_deleted",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Delete date"
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in review", "In review"),
                            ("published", "Published"),
                            ("changes requested", "Changes requested"),
                            ("schedule", "Schedule"),
                        ],
                        default="draft",
                        max_length=255,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("summary", models.TextField(blank=True)),
                ("screenshot", models.CharField(blank=True, max_length=255)),
                ("content_html", models.TextField(blank=True)),
                ("content_json", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_public", models.BooleanField(default=False)),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "categories",
                    models.ManyToManyField(blank=True, to="template.templatecategory"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="company.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
