name: Django CI

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    env:
      DB_NAME: test_db
      DB_USER: root
      DB_PASSWORD: root
    
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Set up MySQL
      run: |
        sudo /etc/init.d/mysql start
        mysql -e 'CREATE DATABASE ${{ env.DB_NAME }};' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
        mysql -e 'SHOW DATABASES;' -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        python -m pip install -r requirements/development.txt  
    - name: Migrate DB
      run: |
        python manage.py migrate --settings=app.settings.development
    - name: Run flake8
      run: |
        flake8
    - name: Run Tests
      run: |
        pytest
        coverage run manage.py test --settings=app.settings.development  --failfast
        coverage report
      env:
          DEBUG: True
          SYSTEM_ENV: GITHUB_WORKFLOW
